name: CI

# It works when PR opened each time
on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Doing code checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ .NET 10 SDK installation
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # 3️⃣ Dependencies restoring
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build project
      - name: Build solution
        run: dotnet build --no-restore --verbosity normal

      # 5️⃣ Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
