name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore
        run: dotnet restore

      - name: Run unit tests (build + test)
        run: dotnet test --no-restore --logger "trx;LogFileName=TestResults.trx" --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}

  # playwright-tests:
  #   name: Playwright Tests
  #   runs-on: ubuntu-latest
  #   needs: build-and-test

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 10.0.x

  #     - name: Restore
  #       run: dotnet restore

  #     - name: Install Playwright browsers
  #       run: |
  #         dotnet tool install --global Microsoft.Playwright.CLI
  #         playwright install --with-deps

  #     - name: Run Playwright tests
  #       run: dotnet test --filter "TestCategory=Playwright"
